# Generated by Django 4.2.7 on 2023-11-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionOfTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Учебная программа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='EducationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Учебная программа')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('duration_hours', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность в часах')),
                ('education_type', models.CharField(blank=True, choices=[('1', 'Обязательное'), ('2', 'Дополнительное')], max_length=255, null=True, verbose_name='Тип обучения')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('direction_of_training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training_center.directionoftraining', verbose_name='Направление обучения')),
            ],
        ),
        migrations.CreateModel(
            name='EducationOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=255, verbose_name='Краткое имя')),
                ('fullname', models.TextField(default='', verbose_name='Полное наименование')),
                ('contacts', models.CharField(default='', max_length=255, verbose_name='Контакты')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Форма проведения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Учебная программа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('aftereffects_verification', models.TextField(blank=True, null=True, verbose_name='Последствия в случае проверок')),
                ('aftereffects_incident', models.TextField(blank=True, null=True, verbose_name='Последствия при НС, ЧП, ЧС')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('education_methods', models.ManyToManyField(to='training_center.educationmethod', verbose_name='Учебные программы')),
            ],
        ),
        migrations.AddField(
            model_name='educationmethod',
            name='education_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training_center.educationorg', verbose_name='Обучающая организация'),
        ),
        migrations.AddField(
            model_name='educationmethod',
            name='event_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training_center.eventform', verbose_name='Форма проведения'),
        ),
        migrations.AddField(
            model_name='educationmethod',
            name='risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training_center.risklevel', verbose_name='Уровень риска'),
        ),
    ]
