# Generated by Django 4.2.7 on 2023-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
        ('training_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='elearning.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='function',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, to='elearning.test', verbose_name='Тесты'),
        ),
    ]
