# Generated by Django 4.2.7 on 2023-11-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_delete_pollentry_alter_course_options_and_more'),
        ('training_center', '0002_function_courses_function_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionoftraining',
            options={'ordering': ['name'], 'verbose_name': 'Вид обучения', 'verbose_name_plural': 'Виды обучения'},
        ),
        migrations.AlterModelOptions(
            name='educationmethod',
            options={'ordering': ['name'], 'verbose_name': 'Учебная программа', 'verbose_name_plural': 'Учебные программы'},
        ),
        migrations.AlterModelOptions(
            name='educationorg',
            options={'ordering': ['display_name'], 'verbose_name': 'Обучающая организация', 'verbose_name_plural': 'Обучающие организации'},
        ),
        migrations.AlterModelOptions(
            name='eventform',
            options={'ordering': ['name'], 'verbose_name': 'Форма проведения обучения', 'verbose_name_plural': 'Формы проведения обучения'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['name'], 'verbose_name': 'Функция должности', 'verbose_name_plural': 'Функции должностей'},
        ),
        migrations.AlterModelOptions(
            name='risklevel',
            options={'ordering': ['name'], 'verbose_name': 'Уровень риска', 'verbose_name_plural': 'Уровни риска'},
        ),
        migrations.AlterField(
            model_name='function',
            name='courses',
            field=models.ManyToManyField(blank=True, to='elearning.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='function',
            name='tests',
            field=models.ManyToManyField(blank=True, to='elearning.test', verbose_name='Тесты'),
        ),
        migrations.AlterModelTable(
            name='directionoftraining',
            table='direction_of_training',
        ),
        migrations.AlterModelTable(
            name='educationmethod',
            table='education_method',
        ),
        migrations.AlterModelTable(
            name='educationorg',
            table='education_org',
        ),
        migrations.AlterModelTable(
            name='eventform',
            table='event_form',
        ),
        migrations.AlterModelTable(
            name='function',
            table='function',
        ),
        migrations.AlterModelTable(
            name='risklevel',
            table='risk_level',
        ),
    ]
