# Generated by Django 4.2.7 on 2023-11-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0003_alter_directionoftraining_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='directionoftraining',
            table='directions_of_training',
        ),
        migrations.AlterModelTable(
            name='educationmethod',
            table='education_methods',
        ),
        migrations.AlterModelTable(
            name='educationorg',
            table='education_orgs',
        ),
        migrations.AlterModelTable(
            name='eventform',
            table='event_forms',
        ),
        migrations.AlterModelTable(
            name='function',
            table='functions',
        ),
        migrations.AlterModelTable(
            name='risklevel',
            table='risk_levels',
        ),
    ]
