# Generated by Django 4.2.7 on 2023-11-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_delete_certificate_delete_certificatefile_and_more'),
        ('elearning', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('access', models.TextField(verbose_name='Доступ')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='PollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.SmallIntegerField(verbose_name='Вес ответа')),
                ('true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Тип сертификата')),
                ('duration_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок действия в годах')),
                ('forever', models.BooleanField(default=False, verbose_name='Бессрочный')),
                ('cost', models.FloatField(blank=True, default='', null=True, verbose_name='Стоимость')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('appointment_date', models.DateField(auto_now_add=True, verbose_name='Дата прохождения опроса')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('state', models.CharField(choices=[(1, 'Назначен'), (2, 'В процессе'), (3, 'Пройден')], default='Назначен', max_length=100, verbose_name='Статус опроса')),
                ('poll_details', models.TextField(verbose_name='Подробные результаты опроса')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Мероприятие')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.poll', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('q_type', models.CharField(choices=[(1, 'Единственный выбор'), (2, 'Множественный выбор'), (3, 'Ранжирование'), (4, 'Сравнение'), (5, 'Текстовый ввод')], default='Тектовый ввод', max_length=100, verbose_name='Тип вопроса')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.SmallIntegerField(verbose_name='Вес вопроса')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('entries', models.ManyToManyField(to='events.pollentry', verbose_name='Варианты ответов')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(to='events.pollquestion', verbose_name='Djghjcs'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Серия')),
                ('number', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Номер')),
                ('desctription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('delivery_date', models.DateField(verbose_name='Дата выдачи')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('valid', models.BooleanField(default=True, verbose_name='Действилтелен')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elearning.courseresult', verbose_name='Электронный курс')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Мероприятие')),
                ('files', models.ManyToManyField(to='events.certificatefile', verbose_name='Файлы')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elearning.testresult', verbose_name='Тест')),
                ('type_of_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.typeofcertificate', verbose_name='Тип сертификата')),
            ],
        ),
    ]
