# Generated by Django 4.2.7 on 2023-11-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_certificatefile_poll_pollentry_typeofcertificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['employee'], 'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='certificatefile',
            options={'verbose_name': 'Файл сертификата', 'verbose_name_plural': 'Файлы сертификатов'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['name'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='contractfile',
            options={'verbose_name': 'Файл договора', 'verbose_name_plural': 'Файлы договора'},
        ),
        migrations.AlterModelOptions(
            name='contracttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип договора', 'verbose_name_plural': 'Типы договоров'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventfile',
            options={'verbose_name': 'Файл мероприятия', 'verbose_name_plural': 'файлы мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Место проведения', 'verbose_name_plural': 'Места проведения'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['name'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='pollentry',
            options={'ordering': ['name'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'ordering': ['name'], 'verbose_name': 'Вопрос опроса', 'verbose_name_plural': 'Вопросы опросов'},
        ),
        migrations.AlterModelOptions(
            name='pollresult',
            options={'ordering': ['name'], 'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опросов'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='typeofcertificate',
            options={'ordering': ['name'], 'verbose_name': 'Тип сертификата', 'verbose_name_plural': 'Типы сертификатов'},
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='certificate',
        ),
        migrations.AlterModelTable(
            name='certificatefile',
            table='certificate_file',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contract',
        ),
        migrations.AlterModelTable(
            name='contractfile',
            table='contract_file',
        ),
        migrations.AlterModelTable(
            name='contracttype',
            table='contract_type',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='eventfile',
            table='event_file',
        ),
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
        migrations.AlterModelTable(
            name='poll',
            table='poll',
        ),
        migrations.AlterModelTable(
            name='pollentry',
            table='poll_entry',
        ),
        migrations.AlterModelTable(
            name='pollquestion',
            table='poll_question',
        ),
        migrations.AlterModelTable(
            name='pollresult',
            table='poll_result',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='typeofcertificate',
            table='type_of_certificate',
        ),
    ]
