# Generated by Django 4.2.7 on 2023-11-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificate',
            table='certificates',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contracts',
        ),
        migrations.AlterModelTable(
            name='contracttype',
            table='contract_types',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='place',
            table='places',
        ),
        migrations.AlterModelTable(
            name='poll',
            table='polls',
        ),
        migrations.AlterModelTable(
            name='pollentry',
            table='poll_entryes',
        ),
        migrations.AlterModelTable(
            name='pollquestion',
            table='poll_questions',
        ),
        migrations.AlterModelTable(
            name='pollresult',
            table='poll_results',
        ),
        migrations.AlterModelTable(
            name='typeofcertificate',
            table='type_of_certificates',
        ),
    ]
