# Generated by Django 4.2.6 on 2023-10-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('fullname', models.TextField()),
                ('func_managers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('func_managers', models.JSONField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.organization')),
                ('parent_subdivision_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='employees.subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('education_plan', models.TextField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.organization')),
                ('subdivision_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('sex', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=255)),
                ('snils', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('photo', models.ImageField(upload_to='images/photo')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('change_password', models.BooleanField(default=True)),
                ('hire_date', models.DateField()),
                ('dismiss_date', models.DateField()),
                ('is_dismiss', models.BooleanField()),
                ('is_banned', models.BooleanField()),
                ('change_logs', models.JSONField()),
                ('history_states', models.JSONField()),
                ('position_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employees.position')),
            ],
        ),
    ]
