# Generated by Django 4.2.7 on 2023-11-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Табельный номер')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='', max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(default='', verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Электронная почта')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспортные данные')),
                ('snils', models.CharField(blank=True, max_length=255, null=True, verbose_name='СНИЛС')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес проживания')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/photo', verbose_name='Фотография')),
                ('login', models.CharField(default=models.CharField(max_length=255, verbose_name='Табельный номер'), max_length=255, verbose_name='Логин')),
                ('password', models.CharField(default=models.CharField(max_length=255, verbose_name='Табельный номер'), max_length=255, verbose_name='Пароль')),
                ('change_password', models.BooleanField(default=True, verbose_name='Необходимо сменить пароль')),
                ('position_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Дата приема')),
                ('dismiss_date', models.DateField(blank=True, default='', null=True, verbose_name='Дата увольнения')),
                ('is_dismiss', models.BooleanField(blank=True, default=False, null=True, verbose_name='Уволен')),
                ('is_banned', models.BooleanField(blank=True, default=False, null=True, verbose_name='Заблокирован доступ на портал')),
                ('change_logs', models.JSONField(blank=True, default=dict, verbose_name='История изменений')),
                ('history_states', models.JSONField(blank=True, default=dict, verbose_name='Состояния работника')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=255, verbose_name='Краткое имя')),
                ('fullname', models.TextField(default='', verbose_name='Полное наименование')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('func_managers', models.ManyToManyField(blank=True, to='employees.employee', verbose_name='Функциональыне руководители')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Тип сертификата')),
                ('duration_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок действия в годах')),
                ('forever', models.BooleanField(default=False, verbose_name='Бессрочный')),
                ('cost', models.FloatField(blank=True, default='', null=True, verbose_name='Стоимость')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код подразделения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата формирования')),
                ('finish_date', models.DateField(blank=True, default='', null=True, verbose_name='Дата расформирования')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('func_managers', models.ManyToManyField(blank=True, to='employees.employee', verbose_name='Функциональные руководители')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.organization', verbose_name='Организация')),
                ('parent_subdivision_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='employees.subdivision', verbose_name='Родительское подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Является руководителем')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('function', models.ManyToManyField(to='training_center.function', verbose_name='Функции')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.organization', verbose_name='Организация')),
                ('subdivision_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.subdivision', verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Серия')),
                ('number', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Номер')),
                ('desctription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('delivery_date', models.DateField(verbose_name='Дата выдачи')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('valid', models.BooleanField(default=True, verbose_name='Действилтелен')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('files', models.ManyToManyField(to='employees.certificatefile', verbose_name='Файлы')),
                ('type_of_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.typeofcertificate', verbose_name='Тип сертификата')),
            ],
        ),
    ]
