# Generated by Django 4.2.7 on 2023-11-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificateFile',
        ),
        migrations.DeleteModel(
            name='TypeOfCertificate',
        ),
    ]
