# Generated by Django 4.2.6 on 2023-10-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='education_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training_center.educationplan'),
        ),
    ]
