# Generated by Django 4.2.7 on 2023-11-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_delete_certificate_delete_certificatefile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['fullname'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['display_name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['name'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
        migrations.AlterModelTable(
            name='position',
            table='position',
        ),
        migrations.AlterModelTable(
            name='subdivision',
            table='subdivision',
        ),
    ]
