# Generated by Django 4.2.6 on 2023-10-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_position_education_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default='', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.CharField(default='', max_length=255, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='snils',
            field=models.CharField(default='', max_length=255, verbose_name='СНИЛС'),
        ),
    ]
