# Generated by Django 4.2.6 on 2023-10-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_birth_date_alter_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default='', verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='change_logs',
            field=models.JSONField(default='', verbose_name='История изменений'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='change_password',
            field=models.BooleanField(default=True, verbose_name='Необходимо сменить пароль'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismiss_date',
            field=models.DateField(default='', verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.TextField(default='', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='history_states',
            field=models.JSONField(default='', verbose_name='Состояния работника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Заблокирован доступ на портал'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_dismiss',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(default=models.CharField(max_length=255, verbose_name='Табельный номер'), max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default=models.CharField(max_length=255, verbose_name='Табельный номер'), max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='images/photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Должность', to='employees.position'),
        ),
    ]
