# Generated by Django 4.2.7 on 2023-11-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='position',
            table='positions',
        ),
        migrations.AlterModelTable(
            name='subdivision',
            table='subdivisions',
        ),
    ]
