# Generated by Django 4.2.7 on 2023-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_table_alter_organization_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['code'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='parent_subdivision_id',
            new_name='parent_subdivision',
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расформирования'),
        ),
    ]
