# Generated by Django 4.2.7 on 2023-11-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0004_alter_directionoftraining_table_and_more'),
        ('employees', '0005_alter_subdivision_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='org_id',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='subdivision_id',
            new_name='subdivision',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='function',
        ),
        migrations.CreateModel(
            name='BasePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('function', models.ManyToManyField(to='training_center.function', verbose_name='Функции')),
            ],
            options={
                'verbose_name': 'Базовая должность',
                'verbose_name_plural': 'Базовые должности',
                'db_table': 'base_positions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='base_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.baseposition', verbose_name='Базовая должность'),
        ),
    ]
