# Generated by Django 4.2.7 on 2023-11-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_org_id_position_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужчина'), ('w', 'Женщина')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='position',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.subdivision', verbose_name='Подразделение'),
        ),
    ]
