# Generated by Django 4.2.7 on 2023-11-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_delete_certificate_delete_certificatefile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='Ссылка на курс')),
                ('max_score', models.FloatField(blank=True, null=True, verbose_name='Максимальный балл')),
                ('check_score', models.FloatField(blank=True, null=True, verbose_name='Проходной балл')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='PollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.SmallIntegerField(verbose_name='Вес ответа')),
                ('true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('max_score', models.FloatField(blank=True, null=True, verbose_name='Максимальный балл')),
                ('check_score', models.FloatField(blank=True, null=True, verbose_name='Проходной балл')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='TestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.SmallIntegerField(verbose_name='Вес ответа')),
                ('true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('appointment_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('start_learning_date', models.DateField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('finish_learning_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('state', models.CharField(choices=[(1, 'Назначен'), (2, 'В процессе'), (3, 'Не пройден'), (4, 'Пройден')], default='Назначен', max_length=100, verbose_name='Статус теста')),
                ('test_details', models.TextField(verbose_name='Подробные результаты теста')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elearning.test', verbose_name='Электронный тест')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('q_type', models.CharField(choices=[(1, 'Единственный выбор'), (2, 'Множественный выбор'), (3, 'Ранжирование'), (4, 'Сравнение')], default='Единственный выбор', max_length=100, verbose_name='Тип вопроса')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.SmallIntegerField(verbose_name='Вес вопроса')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('entries', models.ManyToManyField(to='elearning.testentry', verbose_name='Варианты ответов')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='elearning.testquestion', verbose_name='Djghjcs'),
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('appointment_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('start_learning_date', models.DateField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('finish_learning_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('state', models.CharField(choices=[(1, 'Назначен'), (2, 'В процессе'), (3, 'Не пройден'), (4, 'Пройден')], default='Назначен', max_length=100, verbose_name='Статус курса')),
                ('doc_info', models.TextField(blank=True, null=True, verbose_name='doc_info')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elearning.course', verbose_name='Электронный курс')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
