# Generated by Django 4.2.7 on 2023-11-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollEntry',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Электронный курс', 'verbose_name_plural': 'Электронные курсы'},
        ),
        migrations.AlterModelOptions(
            name='courseresult',
            options={'ordering': ['name'], 'verbose_name': 'Результат курса', 'verbose_name_plural': 'Результаты курсов'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name'], 'verbose_name': 'Электронный Тест', 'verbose_name_plural': 'Электронные Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testentry',
            options={'ordering': ['name'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['name'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['name'], 'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='сourse',
        ),
        migrations.AlterModelTable(
            name='courseresult',
            table='course_result',
        ),
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
        migrations.AlterModelTable(
            name='testentry',
            table='test_entry',
        ),
        migrations.AlterModelTable(
            name='testquestion',
            table='test_question',
        ),
        migrations.AlterModelTable(
            name='testresult',
            table='test_result',
        ),
    ]
