# Generated by Django 4.2.7 on 2023-11-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_delete_pollentry_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='сourses',
        ),
        migrations.AlterModelTable(
            name='courseresult',
            table='course_results',
        ),
        migrations.AlterModelTable(
            name='test',
            table='tests',
        ),
        migrations.AlterModelTable(
            name='testentry',
            table='test_entryes',
        ),
        migrations.AlterModelTable(
            name='testquestion',
            table='test_questions',
        ),
        migrations.AlterModelTable(
            name='testresult',
            table='test_results',
        ),
    ]
